## Player weapon projectile.
##
## One script covers straight bullets, spread pellets, expanding pulses, rail
## beams, and homing sparks so weapon tuning remains data-driven in Main.
extends Node2D
class_name PlayerBullet

var kind := "needle"
var damage := 1
var radius := 4.0
var velocity := Vector2.ZERO
var life_time := 2.0
var pierce := 0
var beam_length := 0.0
var pulse_max_radius := 0.0
var pulse_expand_speed := 0.0
var homing_strength := 0.0
var homing_target: Node2D = null
var bullet_color := Color("#f8f5d8")

var age := 0.0
var hit_ids := {}


## Configures projectile behavior from the weapon stats generated by Main.
func configure(settings: Dictionary) -> void:
	kind = settings.get("kind", kind)
	damage = int(settings.get("damage", damage))
	radius = float(settings.get("radius", radius))
	velocity = settings.get("velocity", velocity)
	life_time = float(settings.get("life_time", life_time))
	pierce = int(settings.get("pierce", pierce))
	beam_length = float(settings.get("beam_length", beam_length))
	pulse_max_radius = float(settings.get("pulse_max_radius", pulse_max_radius))
	pulse_expand_speed = float(settings.get("pulse_expand_speed", pulse_expand_speed))
	homing_strength = float(settings.get("homing_strength", homing_strength))
	homing_target = settings.get("homing_target", null)
	bullet_color = settings.get("color", bullet_color)
	queue_redraw()


## Moves or expands the projectile until its short lifetime expires.
func _process(delta: float) -> void:
	age += delta

	if kind == "pulse":
		radius = min(pulse_max_radius, radius + pulse_expand_speed * delta)
	elif kind != "rail":
		if homing_strength > 0.0 and is_instance_valid(homing_target):
			var desired_velocity := (homing_target.global_position - global_position).normalized() * velocity.length()
			velocity = velocity.lerp(desired_velocity, clampf(homing_strength * delta, 0.0, 1.0))
		position += velocity * delta

	if age >= life_time or (kind == "pulse" and radius >= pulse_max_radius):
		queue_free()

	queue_redraw()


## Tests and records a one-time hit against an enemy.
func try_hit(enemy) -> bool:
	var enemy_id: int = enemy.get_instance_id()
	if hit_ids.has(enemy_id):
		return false
	if not _overlaps_enemy(enemy):
		return false

	hit_ids[enemy_id] = true
	if kind != "pulse" and kind != "rail":
		pierce -= 1
		if pierce < 0:
			call_deferred("queue_free")
	return true


## Draws the projectile in a shape that communicates its weapon type.
func _draw() -> void:
	match kind:
		"rail":
			draw_line(Vector2.ZERO, Vector2(0.0, -beam_length), bullet_color, radius * 2.0, true)
			var glow := bullet_color
			glow.a = 0.16
			draw_line(Vector2.ZERO, Vector2(0.0, -beam_length), glow, radius * 5.0, true)
		"pulse":
			var ring := bullet_color
			ring.a = max(0.2, 1.0 - age / max(life_time, 0.01))
			draw_arc(Vector2.ZERO, radius, 0.0, TAU, 64, ring, 4.0, true)
			var fill := bullet_color
			fill.a = 0.08
			draw_circle(Vector2.ZERO, radius, fill)
		"fan":
			draw_circle(Vector2.ZERO, radius, bullet_color)
			draw_line(Vector2(0.0, radius), Vector2(0.0, -radius * 1.6), Color("#ffffff"), 1.4, true)
		_:
			draw_circle(Vector2.ZERO, radius, bullet_color)
			draw_circle(Vector2.ZERO, radius * 0.45, Color("#ffffff"))


## Uses circle collision for most bullets and a vertical strip for rail beams.
func _overlaps_enemy(enemy) -> bool:
	if kind == "rail":
		var local_enemy: Vector2 = enemy.global_position - global_position
		return abs(local_enemy.x) <= radius + enemy.radius and local_enemy.y <= 0.0 and local_enemy.y >= -beam_length

	return global_position.distance_to(enemy.global_position) <= radius + enemy.radius
